### ISSUE TITLE
Area API

### ISSUE THREAD

**Issue by Snow-Poijio** [john-forkbomb/ccc2020-api#8]

**Comment by shikibu9419** [comment]
- 観光地一覧
- 観光地検索

観光地ごとの投稿一覧は別issue

**Comment by Snow-Poijio** [comment]
Area, Spots(Shop, Tourism), PostのModel周りはこのissueで実装する。

**Comment by Snow-Poijio** [comment]
- [ ] Areaモデル作成
- [ ] Spots::Shopモデル作成
- [ ] Spots::Tourismモデル作成
- [ ] Postモデル作成
- [ ] 各種シードデータの作成
- [ ] GET /api/public/areas/random
    - 自明
    - その観光地の最新のN件の投稿(:idと:image_urlのみ)もひっつけて渡す
- [ ] GET /api/public/areas/:area_id
    - 自明
    - その観光地の最新のN件の投稿(:idと:image_urlのみ)もひっつけて渡す
- [ ] GET /api/ public/areas/search
    - nameとprefectureで検索できるようにする

**Comment by Snow-Poijio** [comment]
画像周りの実装ガッツリ変えるかも

**Comment by shikibu9419** [comment]
>  その観光地の最新のN件の投稿

基本重いからその場で使うor画面遷移後動作をスムーズにしたい場合を除いて避けたいが、その心は？  
あと実装方法わかる？

> 画像周りの実装ガッツリ変えるかも

どのレベルで変える予定？  
モデル増やすとかなら後々ややこしくなる可能性もあるので

**Comment by Snow-Poijio** [comment]
discoいける？

**Comment by shikibu9419** [comment]
今は無理  
16時以降ならおそらくいける

**Comment by Snow-Poijio** [comment]
じゃあ、できるだけ文で説明するわ

**Comment by Snow-Poijio** [comment]
>areaとtourismの違いがわからん

areaは地域,tourismは観光スポット
> 基本重いからその場で使うor画面遷移後動作をスムーズにしたい場合を除いて避けたいが、その心は？
あと実装方法わかる？

その場で使うand画面遷移後動作をスムーズにしたいから。

> 投稿は画像を複数枚持つだろうし

投稿は画像1枚を想定してた。xd的にTikTokみたいな感じやったから。

> それとrandomはさすがに安直すぎない？
「まとめ」「トップ」的な意味合いの方がいいんじゃない

???

**Comment by shikibu9419** [comment]
> areaは地域,tourismは観光スポット

今頃やけど地域テーブルって必要なん  
県コードだけじゃだめ？

> その場で使うand画面遷移後動作をスムーズにしたいから。

その場で使うにしてももうちょい工夫はしたいところっすね  
どこの画面？

> 投稿は画像1枚を想定してた。xd的にTikTokみたいな感じやったから。

あれは当初スライドショーを想定してた  
今は知らんので根津に聞いてみてください

> > それとrandomはさすがに安直すぎない？
> 「まとめ」「トップ」的な意味合いの方がいいんじゃない
> 
> ???

エンドポイント名はドメインや使用用途にしたい派なので`random`エンドポイントの名前が好きじゃないだけ  
今回は別にいいけど、他エンドポイントでランダムに返す需要が出てきたときにややこしい

**Comment by Snow-Poijio** [comment]
> その場で使うにしてももうちょい工夫はしたいところっすね
どこの画面？

一番最初。写真がたくさん出てくるやつ。

> エンドポイント名はドメインや使用用途にしたい派なのでrandomエンドポイントの名前が好きじゃないだけ
今回は別にいいけど、他エンドポイントでランダムに返す需要が出てきたときにややこしい

まじで、areaの中からrandomに1つ選んで返すやつ

**Comment by shikibu9419** [comment]
> 一番最初。写真がたくさん出てくるやつ。

うーん、どうせデータ数少ないし確かにまとめても良さそうだけど  
ちなみに投稿自体はランダムじゃなくてもええん？

> まじで、areaの中からrandomに1つ選んで返すやつ

僕は`recommended`とかにしがちだけどまぁrandomでええか  
ちなみにあの画面を下にスクロールしたら別の観光地出てくるで

**Comment by Snow-Poijio** [comment]
> ちなみに投稿自体はランダムじゃなくてもええん？

よい。

> ちなみにあの画面を下にスクロールしたら別の観光地出てくるで

知ってる。ねずっちと話して、とりあえずはランダムでいいやとなった。

**Comment by shikibu9419** [comment]
地域N件をシャッフルして返さない理由を知りたいな  
N件までは被る心配もないし、地域一覧を返す→別エンドポイントで投稿一覧返す の方がキャッシュ効かせやすくて逆に早い可能性もあるから

**Comment by shikibu9419** [comment]
あと画像のガッツリ変更は文で表しづらい？  
まぁ気になるので後で話しましょう

**Comment by Snow-Poijio** [comment]
> 地域N件をシャッフルして返さない理由を知りたいな

area+投稿n件の方がキャッシュ効かせやすいと思ったからやな。

> あと画像のガッツリ変更は文で表しづらい？

端的に言うとcloudinary使おうとなってる。

**Comment by shikibu9419** [comment]
> area+投稿n件の方がキャッシュ効かせやすいと思ったからやな。

ランダムやろ？  
Fastlyとか挟むのが一番早いだろうけどエンドポイント単位は無理では  
SQLでランダム取得するにしてもキャッシュしたら結果固定されるんじゃないん

> 端的に言うとcloudinary使おうとなってる。

ガッツリが過ぎるな  
S3 + Cloudfrontではダメな理由は？  
画像保存時に複数のサイズで複製するようにしてるし

**Comment by Snow-Poijio** [comment]
> ランダムやろ？

忘れてたわ。showの部分でしか考えてなかったわ。

> S3 + Cloudfrontではダメな理由は？

基本的には速さやな。後は、スマートクロッピングとかの機能が使えるからかな。

**Comment by shikibu9419** [comment]
CDN挟んでる今でも十分早いのにもっと早くなるん？w  
スマートクロッピングもAWS内でできるはずだし、用途も含めてまた話そう
